networks:
  mpnet:
    driver: bridge
services:
  mongo:
    command: mongod --smallfiles --logpath=/dev/null
    container_name: mongo
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    image: mongo:latest
    networks:
      - mpnet
    ports:
    - 27017:27017/tcp
    volumes:
    - ./data/db:/data/db:rw
  mongoguru:
    build:
      context: ./mongoguru
    container_name: mongoguru
    depends_on:
    - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      MONGO_URL: mongodb://mongo:27017/guruDB
    image: mongoguru
    links:
    - mongo
    networks:
      - mpnet
    ports:
    - 5008:5008/tcp
    volumes:
    - /opt/guru/logs:/opt/guru/logs:rw
version: '3.0'