version: '3'
services:
  mongo:
    image: mongo
    build: ./mongo
    hostname: 127.0.0.1
    dns_search: .
    container_name: mongo   
    volumes:
      - /opt/mongo/data/db:/data/db
      - /opt/mongo/logs:/data/logs
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs   
    command: mongod          
    networks:
      - mpnet  
networks:
  mpnet:
    driver: bridge

